# Generated by Django 5.2.7 on 2025-10-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0002_profile_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('N/A', 'Prefer not to say')], default='N/A', max_length=10, null=True),
        ),
    ]
